### ISSUE TITLE
[Easy] Add a Dark Theme button on navbar for dark theme

### ISSUE THREAD

**Issue by piyush97** [piyush97/divvy#4]
[For First timers only] Add a Dark Theme button on navbar for dark theme

**Comment by christoph-codes** [comment]
@piyush97 So I've added the dark theme button, is the expectation to set up all classes to change to dark mode as well or just the provider needs to be setup?

**Comment by christoph-codes** [comment]
![Light Mode](https://user-images.githubusercontent.com/54452490/139556249-1ee24418-3cb1-4480-be18-d0fdde323e2d.png)

![Dark Mode](https://user-images.githubusercontent.com/54452490/139556259-d95ab573-9f5a-43f2-85db-14f344a667d2.png)

**Comment by piyush97** [comment]
#6 Solved this issue, so closing this issue.
